
package graphics;

import singleton.ConfigurationManager;
import singleton.PostgresSQLDBManager;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.ArrayList;

/**
 *
 * @author MSHAO1
 */


public class DataParserPanel extends javax.swing.JPanel {
    
    private class DatasetComboBoxItemChangeListener implements ItemListener {
        @Override
        public void itemStateChanged(ItemEvent e) {
            if (e.getStateChange() == ItemEvent.SELECTED) {
                Object item = e.getItem();
                ConfigurationManager.getConfigurationManager().getConfiguration().setDppStrainTypeId(item.toString());
            }
        }
    }

    /**
     * Creates new form DataParserPanel
     */
    public DataParserPanel() {
        initComponents();
    }
    
    private void initData() {
        dppDatasetComboBox.removeAllItems();
        ArrayList<String> resultList = PostgresSQLDBManager.getAllStrainTypeIDs();
        for (String s : resultList) {
            dppDatasetComboBox.addItem(s);
        }
        dppDatasetComboBox.addItemListener(new DatasetComboBoxItemChangeListener());
        dppDatasetComboBox.setSelectedIndex(0);
        ConfigurationManager.getConfigurationManager().getConfiguration().setDppStrainTypeId(dppDatasetComboBox.getSelectedItem().toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        consoleDisplayScrollPane = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        dppDatasetComboBox = new javax.swing.JComboBox<>();
        outputHeadersCheckBox = new javax.swing.JCheckBox();
        dppStartButton = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(820, 540));
        setMinimumSize(new java.awt.Dimension(820, 540));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        consoleDisplayScrollPane.setViewportView(jTextArea2);

        jLabel1.setText("Select Dataset");

        dppDatasetComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        outputHeadersCheckBox.setText("Output with Headers");
        outputHeadersCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputHeadersCheckBoxActionPerformed(evt);
            }
        });

        dppStartButton.setText("Start");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(consoleDisplayScrollPane)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dppDatasetComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 191, Short.MAX_VALUE)
                        .addComponent(outputHeadersCheckBox)
                        .addGap(184, 184, 184)
                        .addComponent(dppStartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(consoleDisplayScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dppDatasetComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(outputHeadersCheckBox)
                    .addComponent(dppStartButton))
                .addContainerGap(168, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void outputHeadersCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputHeadersCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outputHeadersCheckBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane consoleDisplayScrollPane;
    private javax.swing.JComboBox<String> dppDatasetComboBox;
    private javax.swing.JButton dppStartButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JCheckBox outputHeadersCheckBox;
    // End of variables declaration//GEN-END:variables
}
